### PR TITLE
Update to Webpack 4 hooks API

### LINKED ISSUE #1: Move to the Webpack `.hooks` API
When running the tests I get:

```
⠹ (node:62443) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

https://webpack.js.org/api/plugins/

### PR DESCRIPTION
**Pull request by nullivex**
Fixes #1

### CODE REVIEW

**Comment by sindresorhus** [comment]
What Webpack version introduced hooks? You need to add the appropriate Webpack version as an entry in `peerDependencies` in package.json.

**Comment by nullivex** [comment]
According to the documentation here: https://github.com/webpack/changelog-v5#tapable-base-class-removed

The implementation that was fixed was deprecated from 3 on.

**Comment by nullivex** [comment]
I checked the package.json and it is currently pinned to 4.29.6 which will accept this patch without issue. Please let me know if there is anything else you would like me to do.

**Comment by sindresorhus** [comment]
> Please let me know if there is anything else you would like me to do.

What I commented:

> You need to add the appropriate Webpack version as an entry in peerDependencies in package.json.

**Comment by nullivex** [comment]
@sindresorhus Sorry about the confusion on that. I have added a single commit. See if this corrects the issue.

**Comment by sindresorhus** [comment]
👍 Thanks for the help :)

**Comment by nullivex** [comment]
Thank you for accepting this! :) And you're welcome.

However, I made one last change that I think is correct for the restriction of the peerDependencies especially moving forward to Webpack 5.

Please see: https://github.com/nullivex/add-asset-webpack-plugin/commit/06b067f8de21c59186ada9342a7d380bb07ff81c

We were updating at the same time and Github did not show me the merge until after I completed the edit.

**Pull request merged**
